#!/usr/bin/env bash

# Update package lists optionally
apt-get update

# Install nginx
apt-get install -y nginx
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Restart nginx
killall -s HUP nginx
