#!/usr/bin/env bash
# redirects permanently(301)

sudo apt-get -y update
sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me /var/www/html/index.html permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
