#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

apt-get update
apt-get install -y nginx


echo "Hello World!" > /etc/nginx/html/index.html

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://example.com/new-page;
    }

    error_page 404 /404.html;
    location = /404.html {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
echo "301-moved permanently" > /var/www/example.com/new-page;
service nginx restart
