#!/usr/bin/env bash
# configure Nginx to have a custom 404 page containing the string "C....

sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
}

	error_page 404 /404.html;
	location /404.html {
		root /var/www/html;
		internal;
#		echo "Ceci nest pas une page";
	}
}
EOF'

sudo bash -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'

sudo service nginx restart
