#!/usr/bin/env bash

# Update package repositories and install nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

hostname=$(hostname)

cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Add custom response header
    add_header X-Served-By $hostname;

    # Serve static files from /var/www/html
    root /var/www/html;
    index index.html index.htm;

    # Handle errors
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart Nginx to apply the changes
sudo service nginx restart
