#!/usr/bin/env bash
#installs and configures the loadbalancer haproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y install haproxy=2.9.\*
sudo chown -R $USER:$USER /etc/haproxy/
sudo apt-get -y update
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo  "
frontend myfrontend
	bind *:80
	mode http
	default_backend myservers
backend myservers
	balance roundrobin
	server 335870-web-01 34.229.137.208:80 check
	server 335870-web-02 100.25.181.105:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
